[package]
name = "authentik_sys"
version = "0.35.1"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[workspace]
resolver = "3"
members = ["nss", "pam"]

[[example]]
name = "grpc"

[[example]]
name = "log"

[dependencies]
libc = "0.2.178"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
prost = "0.12"
prost-types = "0.12"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
tonic = "0.11"
tower = { version = "0.5.2", features = ["util" ]}
serde_json = "1.0.147"
sentry = "0.46.0"
cxx = "1.0.192"
windows-sys = "0.61.2"
url = "2.5.7"

[target.'cfg(windows)'.dependencies]
eventlog = "0.3.0"

[target.'cfg(unix)'.dependencies]
syslog = "7.0.0"
