[package]
name = "authentik_sys"
version = "0.35.7"
edition = "2024"

[lib]
crate-type = ["staticlib", "lib"]

[workspace.lints.clippy]
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"

[lints]
workspace = true

[workspace]
resolver = "3"
members = ["nss", "pam"]

[[example]]
name = "grpc"

[[example]]
name = "log"

[dependencies]
cxx = "1.0.192"
hyper-util = "0.1.19"
libc = "0.2.180"
log = "0.4.29"
prost = "0.14"
prost-types = "0.14"
sentry = "0.46.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
tonic = "0.14"
tonic-prost = "0.14"
tower = { version = "0.5.3", features = ["util" ]}
url = "2.5.8"
windows-sys = "0.61.2"

[target.'cfg(windows)'.dependencies]
eventlog = "0.3.0"

[target.'cfg(unix)'.dependencies]
syslog = "7.0.0"
