name: build-ee-wcp

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v5
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: cache/
          key: ee-wcp-deps-${{ runner.os }}
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - shell: bash
        run: |
          make ee/wcp/build
