[package]
name = "authentik_nss"
version = "0.35.3"
edition = "2024"
license = "MIT"

[lib]
name = "authentik_nss"
crate-type = ["cdylib"]

[dependencies]
authentik_sys = { path = ".." }
ctor = "0.6.3"
libc = "0.2.178"
libnss = "0.9.0"
log = "0.4.29"
